version: '3.1'
services:
  adminer:
    image: adminer
    restart: always
    deploy:
      replicas: 3
    ports:
      - 8080:8080
    links:
      - db
      - mongo
    networks:
      - my-network
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - my-network
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - my-network
networks:
  my-network:
