version: '3.1'
services:
  adminer:
    image: adminer
    restart: always
    deploy:
      replicas: 2
    ports:
      - 8080:8080
    links:
      - db
      - mongo
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
