# create your drupal and postgres config here, based off the last assignment
# Drupal with PostgreSQL
#
# Access via "http://localhost:8080"
# Database name: postgres
# Database username: postgres
# Database password: postgres
# Using named vloumes.

version: '2'
services:
  mydrupal:
    image: assignment2-custom-drupal
    build: .
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    restart: always
  mypostgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - drupal-pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  drupal-pgdata:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
